######################################################################
# Automatically generated by qmake (3.0) ?? 8? 13 02:44:24 2017
######################################################################

QT += core gui widgets network multimedia

TEMPLATE = app
TARGET = qqmusic-api
INCLUDEPATH += .

# Input
HEADERS += qqmusic_api.h widget.h
SOURCES += main.cpp qqmusic_api.cpp widget.cpp
